import sqlite3, os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

conn = sqlite3.connect(os.path.join(BASE_DIR,'database','compass.db'))
c = conn.cursor()
c.execute('''CREATE TABLE IF NOT EXISTS resources (id INTEGER PRIMARY KEY AUTOINCREMENT, subject TEXT, topic TEXT, file_type TEXT, link TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS past_papers (id INTEGER PRIMARY KEY AUTOINCREMENT, subject TEXT, year TEXT, paper_link TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS roadmaps (id INTEGER PRIMARY KEY AUTOINCREMENT, career_name TEXT, roadmap_link TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS students (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, email TEXT UNIQUE, password TEXT, course_year TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS chat_history (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER, conversation_name TEXT, message TEXT, role TEXT, timestamp TEXT, is_pinned INTEGER DEFAULT 0)''')
c.execute('''CREATE TABLE IF NOT EXISTS skill_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER, subject TEXT, score INTEGER, total INTEGER, level TEXT, weak_topics TEXT, timestamp TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS about_page (id INTEGER PRIMARY KEY, dev_name TEXT, roll_no TEXT, dev_email TEXT, dev_contact TEXT, dev_photo TEXT, linkedin TEXT, github TEXT, instagram TEXT, college_name TEXT, college_address TEXT, dept_email TEXT, college_contact TEXT)''')
conn.commit(); conn.close()
print("✅ compass.db done!")

conn2 = sqlite3.connect(os.path.join(BASE_DIR,'database','seniors.db'))
c2 = conn2.cursor()
c2.execute('''CREATE TABLE IF NOT EXISTS seniors (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, password TEXT, name TEXT, batch_year TEXT, company TEXT, role TEXT, bio TEXT, linkedin TEXT, github TEXT, instagram TEXT, contact TEXT, profile_photo_link TEXT, achievements TEXT, is_blocked INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1)''')
c2.execute('''CREATE TABLE IF NOT EXISTS senior_posts (id INTEGER PRIMARY KEY AUTOINCREMENT, senior_id INTEGER, post_image_link TEXT, post_caption TEXT, project_link TEXT, date TEXT)''')
conn2.commit(); conn2.close()
print("✅ seniors.db done!")
print("✅ All tables created!")
